### ISSUE TITLE
Cannot run through dijkstra function more than once unless the path is the same

### ISSUE THREAD

**Issue by josephm9** [BlackHatsCS/ALL_Project_2#5]

**Comment by TDouch** [comment]
code has be amended fixing this isssue all it needed wwas a few sets of extra brackets when calling the function

**Comment by B-jibril** [comment]
the issue is fixed

**Comment by wahidul** [comment]
yh i fixed it

**Comment by B-jibril** [comment]
the issues got even worse but i have fixed the problem i have only missed brackets
